const mongoose = require('mongoose');

const SuccessPayment = new mongoose.Schema({
    charge_success_obj_id : {
        type : String,
    },
    payment_object : {
        type : String,
    },
    amount : {
        type : Number,
    },
    amount_captured : {
        type : Number,
    },
    amount_refunded : {
        type : Number,
    },
    user_email : {
        type : String,
    },
    user_name : {
        type : String,
    },
    captured : {
        type : Boolean,
    },
    charge_created_date:{
        type : Date,
    },
    currency : {
        type : String,
    },
    customer_id : {
        type : String,
    },
    invoice_id : {
        type : String,
    },
    paid : {
        type : Boolean,
    },
    payment_method_id : {
        type : String,
    },
    payment_card_brand : {
        type : String,
    },
    card_country : {
        type : String,
    },
    card_exp_month : {
        type : Number,
    },
    card_exp_year : {
        type : Number,
    },
    payment_card_last_4_digits : {
        type : String,
    },
    receipt_url : {
        type : String,
    },
    refunded : {
        type : Boolean,
    },
    status : {
        type : String,
    }


},{
    timestamps:true
});

module.exports = mongoose.model('payment-success',SuccessPayment);


    //   console.log(event.data.object.id)
    //   console.log(event.data.object.amount)
    //   console.log(event.data.object.amount_captured)
    //   console.log(event.data.object.amount_refunded)
    //   console.log(event.data.object.billing_details.email)
    //   console.log(event.data.object.billing_details.name)
    //   console.log(event.data.object.captured)
    //   console.log(event.data.object.created)//time of payment(in miliseconds)
    //   console.log(event.data.object.customer)//customer id(generated by stripe)
    //   console.log(event.data.object.invoice)//invoice id for successive payment (for this customer only)
    //   console.log(event.data.object.paid)//payment successfull or not (Boolean)
    //   console.log(event.data.object.payment_method)//id
    //   console.log(event.data.object.payment_method_details.card.brand)//type of card
    //   console.log(event.data.object.payment_method_details.card.last4)//holds last 4 digits of card
    //   console.log(event.data.object.receipt_url)//receipt url for this success payment
    //   console.log(event.data.object.refunded)//refunded or not (boolean)
    //   console.log(event.data.object.status)